# Generated by Django 3.0.3 on 2020-02-10 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_ref',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Candidate Reference must be 8 alphanumeric characters.', regex='^\\w{8}$')]),
        ),
    ]
