# Generated by Django 3.0.3 on 2020-02-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_auto_20200210_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['score']},
        ),
    ]
